name: e2e tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  full-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: test/package-lock.json
      - name: Install dependencies
        working-directory: test
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: test
        run: npx playwright install --with-deps
      - name: running e2e tests
        working-directory: test
        env:
          DB_CONNECTION_URI: ${{ secrets.DB_CONNECTION_URI }}
        run: npm test -- --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
